# External gems
gems:
 # - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Karima Brooke
subtitle: Community artist
email: karimabrooke.paintings@hotmail.com
name: Karima Brooke
description: Community artist
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
# the base hostname & protocol for your site
url: "https://www.karima-brooke.co.uk/"
cover: "/assets/images/in_the_mediterranean_syrianboydreaming.jpg"
logo:

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
permalink: pretty

# Collections Example
collections:
    gallery:
        output: true
        permalink: /gallery/:path/
    photos:
        output: true

# Defaults Example
defaults:
    -
        scope:
            path: ""
            type: "gallery"
        values:
            layout: "page"

    -
        scope:
            path: "poems"
            type: "pages"
        values:
            layout: "page"

# Disqus comments
# disqus_shortname:

# Google analytics
ga_tracking_id: ""


# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:

  - name: Facebook
    icon: facebook
    username: A Painter
    url:
    desc: Like on Facebook
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/in_the_mediterranean_syrianboydreaming.jpg"
    fb_image_width: 1024
    fb_image_height: 307
    fb_image_type: "image/jpg"

    twitter_image: "/assets/in_the_mediterranean_syrianboydreaming.jpg"

